name: feather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2

  flutter_bloc:
  equatable:
  geolocator:
  dio:
  logger:
  flutter_swiper_null_safety:
    git: https://github.com/lianyagang/flutter_swiper_null_safety.git
  shared_preferences:
  package_info:
  url_launcher:
  pretty_dio_logger:
  fluro:
  timeago:
  app_settings:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner:
  bloc_test: ^8.0.2
  mockito: ^5.0.9
  build_runner:
  http_mock_adapter: ^0.2.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/
